import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#f9f9ff",
        foreground: "#151c27",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "#006c49",
          foreground: "#ffffff",
        },
        secondary: {
          DEFAULT: "#006b5f",
          foreground: "#ffffff",
        },
        tertiary: {
          DEFAULT: "#a43a3a",
          foreground: "#ffffff",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
        // Stitch Custom Design System Colors
        "tertiary-fixed-dim": "#ffb3af",
        "on-primary-fixed": "#002113",
        "surface-container-high": "#e2e8f8",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#62fae3",
        "on-surface-variant": "#3c4a42",
        "surface-dim": "#d3daea",
        "surface-container": "#e7eefe",
        "on-tertiary-fixed-variant": "#842225",
        "secondary-fixed": "#62fae3",
        "error": "#ba1a1a",
        "surface-container-highest": "#dce2f3",
        "tertiary-container": "#fc7c78",
        "on-primary-container": "#00422b",
        "on-primary": "#ffffff",
        "outline": "#6c7a71",
        "surface-variant": "#dce2f3",
        "on-secondary-fixed-variant": "#005047",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "surface-container-low": "#f0f3ff",
        "on-primary-fixed-variant": "#005236",
        "on-background": "#151c27",
        "inverse-primary": "#4edea3",
        "secondary-fixed-dim": "#3cddc7",
        "on-surface": "#151c27",
        "on-tertiary-fixed": "#410005",
        "on-secondary-container": "#007165",
        "primary-container": "#10b981",
        "outline-variant": "#bbcabf",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#2a313d",
        "tertiary-fixed": "#ffdad7",
        "primary-fixed": "#6ffbbe",
        "primary-fixed-dim": "#4edea3",
        "surface": "#f9f9ff",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#711419",
        "surface-bright": "#f9f9ff",
        "surface-tint": "#006c49",
        "inverse-on-surface": "#ebf1ff",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#00201c"
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      spacing: {
        xs: "8px",
        sm: "16px",
        md: "24px",
        lg: "32px",
        xl: "48px",
        gutter: "16px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        "container-max": "1200px",
        base: "4px",
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "caption": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};

export default config;
